name: Remove old artifacts

on:
  schedule:
    # Every day at 3pm taiwan time
    - cron: '0 7 * * *'

jobs:
  remove-old-artifacts:
    runs-on: windows-latest
    timeout-minutes: 10

    steps:
    - name: Remove old artifacts
      uses: c-hive/gha-remove-artifacts@v1
      with:
        age: '2 days' # '<number> <unit>', e.g. 5 days, 2 years, 90 seconds, parsed by Moment.js
        # Optional inputs
        # skip-tags: true
        # skip-recent: 5

  cleanup-artifacts:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v1
      - name: Artifact Cleanup
        uses: jimschubert/delete-artifacts-action@v1
        with:
          log_level: 'error'
          min_bytes: '0'
